apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: allianceit-gke

manifests:
  rawYaml:
    - k8s/orders-service.yaml
    - k8s/inventory-service.yaml
    - k8s/api-gateway.yaml

deploy:
  kubectl: {}

profiles:
  - name: production
    manifests:
      rawYaml:
        - k8s/orders-service.yaml
        - k8s/inventory-service.yaml
        - k8s/api-gateway.yaml
    deploy:
      kubectl: {}